### PR TITLE
Penpot update (Wireframe & mockup)

### PR DESCRIPTION
**Pull request by CHOOSEIT**
This PR aims to describe the changes made to the penpot and also change the links in the README.md redirecting to the penpot.

**Messages to reviewers:**
- I am going to describe below all the main changes I made on the penpot. I however recommend you to go check and test directly on the penpot. 
- Verify that the links to the wireframe and the mockup are working.
- We should merge this branch once everybody changed the penpot with their sprint additions and **updates the links!**.
- **Any of these changes can be discussed; don't hesitate** 😄 

**Changes / Verification made:**
- **Wireframe:** (not significant changes have been made to the wireframe)
Added post popup in profile page in wireframe.
Correct some navigation on posts in the homefeed.
Add click navigation on green bar whenever the user is in a group on the overview page.
Fix add comment button on post page.
Fix start a group button.
Add logout button on wireframe.
_The overall navigation looks good._

- **Mockup:**
Added first username character on profile page inside the circle avatar.
Removed circle avatar with image on post page and replaced it with circle avatar with first username character to keep consistency.
Colored some post vote button with blue color (+ created a general color containing this color).
Added logout button in profile page.
Moved Heatmap to make seemless navigation between filters.
Fixed group popup setting not showing up.
Fixed navigation button back to groups list.
Reworked group page (kept original design idea) reworked: navigation, member list, join button
Rework global top bar (hadn't seemless navigation between pages)
Adds pin navigating to map in the post / comment pop-ups
Add displayName to profile picture
"Your challenges" -> "Challenges"
_The overall navigation looks good._

Thank you in advance for your review ! 🎉 

Acceptance criteria:
- [x] The penpot must be clean, and up to date with the UI
- [x] Change the link on the README

### CODE REVIEW

**Review by gruvw — COMMENTED** [review]
Hey, I just tried the two links in a private browser and can't open them.
Are they supposed to be restricted to logged-in users, or are they supposed to be public (view only) ?

**Review by gruvw — APPROVED** [review]

**Comment by TheTexanCodeur** [comment]
Good job!

The WireFrame and the Mockup now look up-to-date with our ideas. I just have a small comment on the Mockup: when you want to view the two last groups (group screen), you directly arrive on the page where you're in the group. I think that this is inconsistent with the other groups where you first arrive on the "join" screen.

**Review by TheTexanCodeur — COMMENTED** [review]
The links work correctly!

**Review by TheTexanCodeur — APPROVED** [review]
LGTM now!

**Pull request merged**
