### PR TITLE
Bump version 0.4.3

### PR DESCRIPTION
**Pull request by gruvw**

### CODE REVIEW

**Review by Aderfish — APPROVED** [review]
LGTM

**Review by yoannLafore — APPROVED** [review]
Very good !
Thanks for your work :tada:

**Review by CHOOSEIT — APPROVED** [review]
Looks good to me 💯

**Review by JoachimFavre — APPROVED** [review]
A huge PR, this is amazing. Thank you for all your work this sprint! :)

**Review by camillelnne — APPROVED** [review]
🥳

**Review by TheTexanCodeur — APPROVED** [review]
LGTM 🚀

**Pull request merged**
