### PR TITLE
Geolocation provider

### PR DESCRIPTION
**Pull request by yoannLafore**
Hello,
This PR aims to expose the geolocation service.
To do so, it adds a `Provider` for the geo location service and adds the location permissions to the Android Manifest.
Thanks for reviewing this PR !

### CODE REVIEW

**Review by gruvw — APPROVED** [review]
LGTM

**Comment by camillelnne** [comment]
LGTM too :)

**Review by camillelnne — APPROVED** [review]
LGTM too :)

**Comment by yoannLafore** [comment]
Thanks for your review ! 
I'll perform the merge

**Pull request merged**
