### PR TITLE
Post card in profile

### LINKED ISSUE #197: Fix the profile page UI, to use a card instead of setting the background colour manually
Acceptance criteria:
- Post, comments and badges are now card widgets.
- Their UI (mainly color) is consistent with the feed UI.

### PR DESCRIPTION
**Pull request by camillelnne**
Fix #197.
Post, comments and badges are now displayed using cards.

**Features:**
- Refactor of post and comment widget
- Refactor of badge widget

**Acceptance criteria:**
- [x] Post, comments and badges are now card widgets.
- [x] Their UI (mainly color) is consistent with the feed UI.

Tested on physical device and by running all unit tests.

### CODE REVIEW

**Review by CHOOSEIT — CHANGES_REQUESTED** [review]
Clean PR 💯 . Thank you 

I have few comments that are more general.

I think that since you replaced the `Container` by `Card`, the `shadow` parameters of the widgets are not used anymore. Since we would like to mimic the home feed, I think that we can completely remove them.

Additionally, I think that the profile page changed a bit with your changes. The badges seems smaller, and I think that there is a huge space between the posts / comments in their respective list.
I think that the badge are ok, but I think that spaces between the posts/comment are too large compared to our mockup.

**Comment by camillelnne** [comment]
> Clean PR 💯 . Thank you
> 
> I have few comments that are more general.
> 
> I think that since you replaced the `Container` by `Card`, the `shadow` parameters of the widgets are not used anymore. Since we would like to mimic the home feed, I think that we can completely remove them.
> 
> Additionally, I think that the profile page changed a bit with your changes. The badges seems smaller, and I think that there is a huge space between the posts / comments in their respective list. I think that the badge are ok, but I think that spaces between the posts/comment are too large compared to our mockup.

Thanks for the catch for the shadow!
For the badges, I chose not to focus to much in getting a perfect design since we will be defining in the future what they will look like.
For the other cards, I didn't notice it, I'll fix it, thanks.

**Comment by camillelnne** [comment]
8566d7aaa4724f98a08d55e740e7ff14fb15a729: Removed shadow parameters, now useless because we are using cards.
14e5956d0de049decb01628cea81585b80eaf8ad: Removed the separator, like I did in the badge, now the posts and comments are closer to each other.
Applied all requested changes, ready for a new review! :)

**Review by CHOOSEIT — APPROVED** [review]
Looks good to me now ! 💯 

Great job 😄  Thank you !

**Pull request merged**
